modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="gatorlab"
version="${file.jarVersion}"
displayName="GatorLab"
authors="reetam"
[[dependencies.gatorlab]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gatorlab]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"